### ISSUE TITLE
Dracut-initqueue timeouts - no network

### ISSUE THREAD

**Issue by veehexx** [ventoy/PXE#10]
Occurs on both 1.0.11 & 1.0.12.
machines are VM's inside Proxmox8. iventoy server is RockyLinux, multiple clients have been tested with various settings; bios and uefi mode, virtio and E1000 NIC's.

iventoy boots and displays iso's as expected.
Select the supported 'Fedora-Workstation-Live-x86_64-38-1.6.iso' and after 140 secs of a black screen, i will start to see the console fill up with the following screenshot.
after 320 secs it will drop down to emergency/maintenance prompt. Notice that there is no ip address.

![image](https://github.com/ventoy/PXE/assets/1247183/2dfc361e-5272-4f59-bd9a-a1243ebe72bb)
![image](https://github.com/ventoy/PXE/assets/1247183/92c170eb-88a2-43b7-9a6f-c290a4363225)

**Comment by ventoy** [comment]
Run  `cat  /ventoy/log`  here and upload the log.

**Comment by veehexx** [comment]
server log attached. i've ran a fresh PXE boot starting at 2023/07/17 10:53:50.434.

[iventoy_1-0-12.log](https://github.com/ventoy/PXE/files/12068113/iventoy_1-0-12.log)

**Comment by ventoy** [comment]
Please run `cat /ventoy/log` in the dracut shell after timeout.

**Comment by veehexx** [comment]
`/ventoy/log` doesnt exist. no `/ventoy` at all.
![image](https://github.com/ventoy/PXE/assets/1247183/ed477df9-9256-4184-9afe-637cd2443dfc)



in case it helps:
I tried another image - `Rocky-8.8-x86_64-dvd1.iso`, and getting similar dracut-initqueue timeouts. This seems to be clearer that theres an iSCSI issue (iSCSI is used to mount the iso, correct?)
![image](https://github.com/ventoy/PXE/assets/1247183/bb340c4f-634a-4e77-9961-ef5ba2a21f88)

**Comment by ventoy** [comment]
Try latest 1.0.14

**Comment by veehexx** [comment]
1.0.14 working for `Fedora-Workstation-Live-x86_64-38-1.6.iso`. Boots to the expected Live gnome desktop! Awesome!

`Rocky-8.8-x86_64-dvd1.iso` image is still failing but with different problem.

`vi /run/initramfs/rdsosreport.txt`. Theres many lines of the dracut-initqueue timeout before it drops down to emergency prompt:
![image](https://github.com/ventoy/PXE/assets/1247183/54274c4e-0e4b-425b-9a99-f39d1bb9cdce)

This time we do have `cat /ventoy/log`, so .14 has improved something:
![image](https://github.com/ventoy/PXE/assets/1247183/cd336385-7ebe-4c1e-a6b0-274b70b6f6c2)

**Comment by ventoy** [comment]
Try 1.0.15

**Comment by veehexx** [comment]
.16 working with `Rocky-8.8-x86_64-dvd1.iso`. all issues fixed!
