### ISSUE TITLE
Malware detected with iVentoy

### ISSUE THREAD

**Issue by asheroto** [ventoy/PXE#16]
Hello,

I've added iVentoy to the [Chocolatey community repository](https://community.chocolatey.org/packages). I published version 1.0.6 and it was approved today.

The problem though with current versions, is that there are an increasing number of malware detections with iVentoy...

**Version 1.0.6 - 12 detections:**
https://www.virustotal.com/gui/file/9d3d0a2ad1811eae4fa3f095149f53511e74276993a44f4ff010ec0467b6e266

**Version 1.0.8 - 3 detections:**
https://www.virustotal.com/gui/file/4cfb8b9fa531622d7a921489e60fb8d66efd1983132d441f9b03ecfb105cc050

**Version 1.0.11 - 17 detections:**
https://www.virustotal.com/gui/file/a1104207e58b9cbe38a7f23f2cae286b909c61033f36b3f2c94da74176533445

**Version 1.0.16 - 20 detections:**
https://www.virustotal.com/gui/file/34aeb1e1a1d4a766b2f481e6bd5237e3fcd8effb70768efeaee679fa360ae6a9

Was something added to the code to make these detections show up? I'm sure they are false positives, but something must have changed that is triggering these.

With so many detections, I do not think I will be able to get this approved for the Chocolatey community repository.

Any thoughts? Perhaps some new feature was added that is triggering this.

I'd like to add it to Chocolatey so that users can just type "choco install iventoy".

Alternatively, if you could provide a strong reason to explain the detections, I may be able to get the package manually approved.

**From the review team at Chocolatey:**
"In order to get this exempted, despite the AV detections, is some sort of official statement from the software author about the detections being expected **which can be linked to** from the package description."

Can you provide an official statement and have it on iVentoy.com explaining why it may show as a false positive? That would help avoid people thinking that iVentoy contained malicious code.

I went ahead and submitted false positive reports to Avast, AVG, VIPRE, BitDefender, GDATA, and Webroot.

According to the behavior tab of VirusTotal, some program.exe is running from the desktop?
https://www.virustotal.com/gui/file/34aeb1e1a1d4a766b2f481e6bd5237e3fcd8effb70768efeaee679fa360ae6a9/behavior

![image](https://github.com/ventoy/PXE/assets/49938263/00110a8c-15fe-4366-b3a0-beb39d540567)

But according to sysmon monitoring, I don't see that happening. So I think that's one of the reasons it's a false positive.

Maybe there's something extra in the code?

Thank you

**Comment by justinthegeek** [comment]
It still would be great to hear from the author, but I rechecked 1.0.16 and as of today, there are only 6 detections. I'd have to imagine that it's a false positive.

**Comment by asheroto** [comment]
Yeah! So some update on this. I was able to get all of the false positive reports I submitted to AV providers reviewed and now the classification/determination status has changed to good. 😎

Hoping the next release has similar findings.

I will keep trying to submit reports for the rest of detections.

**Comment by asheroto** [comment]
Once VirusTotal updates their definitions we'll be closer to less detections.

**Comment by AtA3301** [comment]
20 detections on **_iventoy-1.0.17-win64-free.zip_**

https://www.virustotal.com/gui/file/c043fd4c5a7f63d3f4c4e980f5d0203d5f8d9e60e07150032dcd2e25a282dc1e/detection

Pretty sure it's because it's a PE/PXE boot tool, which the various vendors panic about by default.

**Comment by asheroto** [comment]
I have submitted false positive reports to several other AV vendors and so far the following have e-mailed me back to confirm they have whitelisted iVentoy:
- McAfee
- BitDefender
- Avast
- VIPRE
- G DATA

I just heard back from three of these this morning, so the whitelisting may not reflect in VirusTotal.

I am waiting the following:
- Symantec
- Trend Micro
- Malwarebytes

**Comment by asheroto** [comment]
So far almost every major AV vendor I've contacted has whitelisted iVentoy. 😎🆒

Still waiting to hear back from others. I've been updating the list above.

**Comment by samhnky** [comment]
ESET appears to still be blocking this.

**Comment by asheroto** [comment]
According to VirusTotal, ESET does not detect it for any of the files. Are you sure your definitions are updated? If so, could you please send me a screenshot of the detection and I will pass it along to the ESET support team? Thanks.

**Comment by samhnky** [comment]
![ESET Blocking](https://github.com/ventoy/PXE/assets/32919298/0e765987-38f6-4f9a-942a-ad0c7f89d7db)
This is the error I get when trying to download the latest Windows file: [iventoy-1.0.17-win64-free.zip](https://github.com/ventoy/PXE/releases/download/v1.0.17/iventoy-1.0.17-win64-free.zip)

So I tried to do a runaround and opened up the Windows Sandbox environment and downloaded iVentoy there, since ESET is not running in the SandBox the download is allowed. I then attempted to copy the extracted downloaded file from the Sandbox onto my computer and some of the files just never made it.

**Comment by asheroto** [comment]
Thanks. I checked VirusTotal and also Hybrid-Analysis and according to each, ESET doesn't detect it. Perhaps it's detecting the URL as suspicious? I'm going to go ahead and report the download URL as a false positive, but can you also try to report it through the ESET program? Details here https://support.eset.com/en/kb141-submit-a-virus-website-or-potential-false-positive-sample-to-the-eset-lab#esetproduct

I am sending an e-mail to the e-mail address mentioned on that page as well.

**Comment by samhnky** [comment]
I didn't install or run iVentoy in Sandbox, All I did was use it to download the zip file, then I tried copying it out of the Sandbox to my desktop computer, thus bypassing the link being accessed by the ESET protection, but it seems that ESET is deleting files from my Desktops non sandbox storage as I copy files over...

**Comment by asheroto** [comment]
Interesting. Well I went ahead and submitted the URL and file to them, so we'll see what they say.

**Comment by samhnky** [comment]
I don't know if they already processed it, but the download just processed for me, and whatever was killing my access to copy the DLL files over to the computer stopped as well... I now have it downloaded and extracted.

**Comment by asheroto** [comment]
Heard back from ESET. They said

```
Thank you for your submission.
We are going to unblock the downloads for the 1.0.17 version.
```

**Comment by asheroto** [comment]
## iVentoy 1.0.18

I am keeping this list up to date to track the AV vendor whitelist status of iVentoy

**Last Updated**: 2023-08-13
**Detection Count When Started**: 2-8
**Current Detection Count**: 2-8

| Filename                           | Version      | False Positive AV Detected By                   |
|------------------------------------|--------------|-------------------------------------------------|
| [iventoy-1.0.18-win64-free.zip](https://www.virustotal.com/gui/file/08d52d845dcb2a54170225168cffbc580ceea66c8548821712e7a7f376d9e776)       | 1.0.18_win64 | Elastic, McAfee                               |
| [iventoy-1.0.18-win32-free.zip](https://www.virustotal.com/gui/file/b37891706fcec473a17306e085a9229c851ea1fa6e1ab3b44ee1f8720513d9da)       | 1.0.18_win32 | Arcabit, BitDefender, MaxSecure, Microsoft  |
| [iVentoy_64.exe](https://www.virustotal.com/gui/file/f92c67f787b1d9eab0188c546cf588e24ebaf479c13ab69ed8f8a490c48cccc2)                     | 1.0.18_win64 | Cynet, Elastic, McAfee                       |
| [iVentoy_32.exe](https://www.virustotal.com/gui/file/4e7be4f3dba63000f3445cc254f807a918b02156f6dbec914fec72475046b917)                     | 1.0.18_win32 | Arcabit, BitDefender, Bkav Pro, Cynet, DeepInstinct, MaxSecure, Microsoft, Trapmine |

I have e-mailed the AV vendors mentioned above regarding a false positive detection of iVentoy.

**AV vendors that have whitelisted this version of iVentoy:**
(none yet)

**AV vendors that have partially whitelisted iVentoy:**
(none yet)

**Awaiting reply from AV vendor support:**
- Elastic
- McAfee
- Arcabit
- BitDefender
- MaxSecure
- Microsoft
- Cynet
- Bkav Pro
- DeepInstinct
- Trapmine

**Comment by asheroto** [comment]
Updated just now on 2023-08-19.

A few vendors have been unresponsive. They may not be in business. If I do not hear back in the next week I will contact VirusTotal about removing their AV from the VT website.

**Comment by asheroto** [comment]
Closing this as it appears to be an ongoing issue, although many AV vendors have replied.
