### ISSUE TITLE
Boot from SAN device 0xe0 failed

### ISSUE THREAD

**Issue by montvid** [ventoy/PXE#40]
Intel NUC pc boots to iventoy but can not load any iso files. Other computers on the network boot iso files fine. I tried booting ipxe 1.21.1 from usb with no problems. It boots Iventoy but trying to load iso it shows : 
Boot from SAN device 0xe0 failed: Error 0x7f222091
The nic is rtl18168 - the uefi bios shows it is using undi drivers.
![IMG_20231122_155833](https://github.com/ventoy/PXE/assets/23270059/f395b185-efc4-446d-ba5a-89d95e87e6a7)
![IMG_20231122_155328](https://github.com/ventoy/PXE/assets/23270059/de9716fa-2a15-40bd-80a7-2d3158932598)

**Comment by montvid** [comment]
Solved the problem choosing ipxe.efi option and 800x600 resolution to boot windows 11. Ubuntu and Fedora boot on 1920x1080 fine. Windows does not install, have to mount the iso manualy from cmd and then it works.
![IMG_20231124_100557](https://github.com/ventoy/PXE/assets/23270059/99132684-4e16-4c39-b156-b299a28ac635)

**Comment by bigjeffuk** [comment]
I have come across the same issue booting from a new HP 250 R G9. After leaving the machine on for a while I get the 0x7f222091 error. 

NIC is a RTL8111HSH-CG

Changing resolution etc still fails to boot. Im using the software in 'external' mode and have 'iventoy_loader_16000' set on DHCP the documentation only suggests using different options when using 'ExternalNet' mode. Incidentaly in the log I get the following so presume the correct loader is being used. 

`2025/12/01 12:12:21.480 [DHCP] Recv DHCP Offer Request from 4ccf-7c02-0dba, response DHCP ACK
2025/12/01 12:12:21.493 [TFTP] Parse tftp option(tsize,0)
2025/12/01 12:12:21.493 [TFTP] Parse tftp option(blksize,1468)
2025/12/01 12:12:21.493 [TFTP] Unsupported tftp option windowsize 4
2025/12/01 12:12:21.493 [TFTP] TFTP RRQ client 172.28.1.200:1885 download <ipxe.x64.snponly.efi.0> start ...
2025/12/01 12:12:21.493 [TFTP] Start send file ipxe.x64.snponly.efi.0 to 172.28.1.200:1885 with blksize 1468, has oack 1
2025/12/01 12:12:21.494 [TFTP] Recv an ERROR opcode pkt from client 172.28.1.200:1885.`

I have also tried using the inbuilt DHCP server. 

Im not sure if the errors are related. 

Just to confirm the software works on other machines. - Secure boot is not on.
