### ISSUE TITLE
iventoy能否支持在树莓派上搭建PXE服务器

### ISSUE THREAD

**Issue by SiLverCraws** [ventoy/PXE#45]
我正在研究使用树莓派搭建PXE服务器，看到iventoy方案比较方便就尝试了一下，但是使用官方的文件包还是尝试使用源码，都没有安装成功，请给一个解决方案，谢谢
![image](https://github.com/ventoy/PXE/assets/46990354/6f31cb41-3276-4c32-a4ea-fc0a002d4ee6)

**Comment by RandomOS** [comment]
不客气，不支持 linux aarch64

**Comment by devome** [comment]
aarch64需要付费购买许可才可以使用。

**Comment by ventoy** [comment]
iVentoy 软件本身只能运行在 x86 CPU的机器上。 
iVentoy 支持 aarch64 的意思是，支持 aarch64 的客户端通过PXE安装系统。
