### ISSUE TITLE
iVentoy not launching inside Proxmox (W10-11 VMs running in UEFI mode)

### ISSUE THREAD

**Issue by mindspies** [ventoy/PXE#63]
I've used iVentoy in the past with Windows 10 under Proxmox and had 0 problem using standard (LEGACY BIOS) option.

In UEFI mode (Proxmox), I've tried with various configuration options, with Windows 10 and 11, but something seems to be blocking the launch of iVentoy executable. (Note that I saw the "more option" and authorised it via the SmartScreen popup).

The thing is I'd wish to use iVentoy in UEFI mode (inside a Proxmox VM), because the only option to do PCIe passthrough for my SATA card is to be in UEFI mode.

Could someone point out what could make work iVentoy executable in UEFI mode under Windows 10 or 11 using a Proxmox Hypervisor?

Thanks in advance.

**Comment by ventoy** [comment]
Have you ever installed the VC++ Runtime Library?

> 
> **No response when double-click iVentoy exe**
> Please install the VC++ runtime library for VS2019 firstly. [Microsoft Official Download Link](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170)

**Comment by mindspies** [comment]
Thanks for you help it is now working! I really appreciate!

**Comment by mindspies** [comment]
I should have read the FAQ lOl.
