### ISSUE TITLE
iventoy : PXE-E53 No boot file name received PXE-M0F Exiting PXE ROM

### ISSUE THREAD

**Issue by geryescalier** [ventoy/PXE#68]
Hello everyone, I have a similar problem as the following post https://forums.ventoy.net/showthread.php?tid=2835
I signed up for the forum but I have not received an email to confirm my account, for that reason I have not been able to post there.

Attached is a screenshot of the message that the computer displays when it does not obtain the boot file.

![image](https://github.com/ventoy/PXE/assets/5092925/7388cc20-dc2a-4207-9ece-e40779e0dc9b)

In principle, the problem I have is that I cannot configure the file with which I boot from the network on my ZTE brand router owned by ISP.

The alternative would be to disable the dhcp service on my router and configure a dhcp server that points to the iventoy network boot file, on the same machine that has iventoy running?

If I understand correctly, Iventoy does not have its own dhcp service.

Any help welcome, thank you very much!

**Comment by ZeroQI** [comment]
If your DHCP is still running on your router, you need to set the DHCP in external mode most probably so iVentoy act as proxy DHCP
[****](https://forums.ventoy.net/showthread.php?tid=2700)

**Comment by geryescalier** [comment]
Hello, thank you for responding, I have already solved it, I have used my own router, my ISP's router does not allow me to configure next server, I have also made some changes to the dhcp configuration, since the iventoy documentation gives an example but it doesn't work in dhcp.
I attach screenshots after finishing the configurations, server and laptop, ready to install Debian 12

![ivetoymenu0](https://github.com/ventoy/PXE/assets/5092925/457f60a9-b61a-449b-9491-17e4cc6c3f4d)


![portatilivetoy](https://github.com/ventoy/PXE/assets/5092925/818edc13-cbf4-46e6-bd75-4ee8ef19033e)
