### ISSUE TITLE
iVentoy won't boot the new LTSC 2024 ISO (storage driver needed)

### ISSUE THREAD

**Issue by bykidi** [ventoy/PXE#72]
https://cloud.mail.ru/public/nNTY/BUny5RvHt/en-ru_windows_11_enterprise_ltsc_2024_with_update_26100.560_aio_6in1_x64_v24.05.18_by_adguard.iso

Can't boot this iso, it asks for a storage driver for some reason, which is not needed.
Booting using a regular ventoy works fine

**Comment by Benoit221** [comment]
Hello,

I encoutered some similar issue with Windows Server 2025 preview. Isn't it a problem with network driver ? When booting using iventoy you need to have network functionnal to communicate with the nbd server.
To ensure of that, you can do ALT + F10 and verify with ipconfig 

Best regards,
Benoit

**Comment by Benoit221** [comment]
Sorry, seems to be temporarly trouble. I tryed again and it's working.

**Comment by bykidi** [comment]
> you need to have network functionnal to communicate with the nbd server

and there isn't any...
what would be a solution in that case?

**Comment by Benoit221** [comment]
You should check this issue https://github.com/ventoy/PXE/issues/28

**Comment by bykidi** [comment]
> You should check this issue #28

it is probably worth a shot trying to include the networking part of SDI drivers for my windows images...
thanks for hinting for the root of the issue.
closed as non an issue with iventoy
